### PR TITLE
add hidden spot list

### PR DESCRIPTION
**Pull request by StrongCurrent**
have implemented my first user story and the result can be seen here. i am happy about the first code review and interested to see if i have done everything right in your eyes. looking forward to your feedback thank you very much.

### CODE REVIEW

**Review by AliaksandraNovikava — CHANGES_REQUESTED** [review]
Hey @StrongCurrent.
A really good start - congratulations 🚀

I left some comments, trying to help you make your code cleaner👨‍💻
My last comment is the most significant of all, I would say.

Keep up the good work🔥

**Comment by StrongCurrent** [comment]
Hey @AliaksandraNovikava,

thank you for your compliment and the great code review. you are absolutely right with your comments. i have updated the whole code. i am looking forward to further feedback. thanks again. best regards

**Review by CorneliusMoe — APPROVED** [review]
First PR looking good, you implemented the suggested changes, all great 👍

**Comment by StrongCurrent** [comment]
Hey @CorneliusMoe, thank you for your feedback and the approval.

**Pull request merged**
